#!/usr/bin/env python3
"""Generate complete bibleData.js with Genesis (50) + Exodus (40)."""

import os, json

def js_str(s):
    """Escape a string for JS, preserving newlines as \\n."""
    s = s.replace('\\', '\\\\')
    s = s.replace('"', '\\"')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '')
    return s

def chapter_js(n, title, text, reflection, q, a):
    return '''      {{
        number: {n},
        title: "{title}",
        text: "{text}",
        reflection: "{reflection}",
        activity: {{
          question: "{q}",
          answer: "{a}"
        }}
      }}'''.format(
        n=n, title=js_str(title),
        text=js_str(text), reflection=js_str(reflection),
        q=js_str(q), a=js_str(a)
    )

# Build all books
books = []

# ====== GENESIS (50 chapters) ======
genesis_chapters = []

genesis_chapters.append(chapter_js(1,
    "A Criação dos Céus e da Terra",
    "No princípio, criou Deus os céus e a terra. A terra era sem forma e vazia; e havia trevas sobre a face do abismo; mas o Espírito de Deus pairava sobre a face das águas.\n\nE disse Deus: Haja luz. E houve luz. E viu Deus que a luz era boa; e fez separação entre a luz e as trevas. E chamou à luz Dia, e às trevas chamou Noite. E foi a tarde e a manhã, o primeiro dia.\n\nE disse Deus: Haja uma expansão no meio das águas. E chamou a expansão Céus. E foi a tarde e a manhã, o segundo dia.\n\nE disse Deus: Ajuntem-se as águas debaixo dos céus num lugar, e apareça a porção seca. Produza a terra erva verde e árvores frutíferas. E foi a tarde e a manhã, o terceiro dia.\n\nE disse Deus: Haja luzeiros no firmamento dos céus. E fez Deus os dois grandes luzeiros e as estrelas. E foi a tarde e a manhã, o quarto dia.\n\nE disse Deus: Produzam as águas abundantemente répteis de alma vivente, e voem as aves. E criou Deus as grandes baleias. E foi a tarde e a manhã, o quinto dia.\n\nE disse Deus: Produza a terra alma vivente. Façamos o homem à nossa imagem. E criou Deus o homem à sua imagem; homem e mulher os criou.\n\nE viu Deus tudo quanto tinha feito, e eis que era muito bom. E foi a tarde e a manhã, o sexto dia.\n\nAssim os céus e a terra foram acabados. E havendo Deus acabado no sétimo dia a sua obra, descansou. E abençoou Deus o sétimo dia e o santificou.",
    "A criação não é fruto do acaso. Cada detalhe foi planejado com ordem e propósito. Deus separa, organiza e preenche. O ser humano, criado à imagem de Deus, recebe não apenas a vida, mas também um chamado: cuidar da criação e refletir o caráter do Criador. O descanso de Deus no sétimo dia não é por cansaço, mas para estabelecer um ritmo de confiança e comunhão. Ele nos convida a parar, contemplar e reconhecer que tudo vem dEle.",
    "O que Deus criou no primeiro dia e como chamou cada parte?",
    "Deus criou a luz, separando-a das trevas. Chamou à luz 'Dia' e às trevas 'Noite' (Gênesis 1:3-5)."
))

genesis_chapters.append(chapter_js(2,
    "O Jardim do Éden e a Criação do Homem e da Mulher",
    "Assim os céus e a terra foram acabados com todo o seu exército. E o SENHOR Deus formou o homem do pó da terra e soprou em suas narinas o fôlego da vida; e o homem foi feito alma vivente.\n\nE plantou o SENHOR Deus um jardim no Éden, da banda do Oriente, e pôs ali o homem que tinha formado. E fez brotar da terra toda árvore agradável à vista e boa para comida, e a árvore da vida no meio do jardim.\n\nE tomou o SENHOR Deus o homem e o pôs no jardim do Éden para o lavrar e guardar. E deu-lhe ordem: De toda árvore do jardim comerás, mas da árvore do conhecimento do bem e do mal não comerás; porque no dia em que dela comeres, certamente morrerás.\n\nE disse o SENHOR Deus: Não é bom que o homem esteja só; far-lhe-ei uma ajudadora idônea. E formou uma mulher da costela que tomou do homem, e trouxe-a a Adão.\n\nE disse Adão: Esta é agora osso dos meus ossos e carne da minha carne; será chamada varoa, porquanto do varão foi tomada. Portanto deixará o varão o seu pai e a sua mãe e apegar-se-á à sua mulher, e serão ambos uma carne.\n\nE ambos estavam nus, o homem e a sua mulher, e não se envergonhavam.",
    "Este capítulo revela a intimidade do relacionamento de Deus com a humanidade. Ele não criou o homem e o abandonou; plantou um jardim, deu trabalho significativo e estabeleceu comunhão. A criação da mulher mostra que não fomos feitos para viver isolados. O casamento é apresentado como uma aliança de parceria, intimidade e unidade. Deus viu que não era bom que o homem estivesse só.",
    "Por que Deus criou a mulher e qual foi a reação de Adão?",
    "Deus criou a mulher porque não era bom que o homem estivesse só. Adão a reconheceu como 'osso dos meus ossos e carne da minha carne' (Gênesis 2:18, 23)."
))

genesis_chapters.append(chapter_js(3,
    "A Queda do Homem e Suas Consequências",
    "E a serpente era mais astuta que todas as alimárias do campo. E disse à mulher: É assim que Deus disse: Não comereis de toda árvore do jardim?\n\nA mulher disse: Do fruto das árvores comeremos, mas do fruto da árvore que está no meio do jardim, disse Deus: Não comereis dele, para que não morrais.\n\nEntão a serpente disse: Certamente não morrereis. Porque Deus sabe que no dia em que dele comerdes se abrirão os vossos olhos, e sereis como Deus.\n\nE vendo a mulher que aquela árvore era desejável para dar entendimento, tomou do seu fruto e comeu, e deu também a seu marido, e ele comeu. Então foram abertos os olhos de ambos, e conheceram que estavam nus.\n\nE ouviram a voz do SENHOR Deus que passeava no jardim; e esconderam-se. E chamou o SENHOR Deus a Adão: Onde estás?\n\nE o SENHOR Deus disse à serpente: Porei inimizade entre ti e a mulher, e entre a tua semente e a sua semente; esta te ferirá a cabeça, e tu lhe ferirás o calcanhar.\n\nE o SENHOR Deus fez túnicas de peles a Adão e à sua mulher e os vestiu. E lançou-os fora do jardim do Éden.",
    "A queda não começou com a desobediência, mas com a dúvida sobre a bondade de Deus. A serpente questionou a Palavra de Deus. Mas a graça brilha em meio ao juízo: Deus promete um Redentor que esmagaria a cabeça da serpente. Mesmo quando nos escondemos, Deus nos busca: 'Onde estás?' — não para condenar, mas para restaurar.",
    "Qual foi a promessa de Deus em meio à maldição contra a serpente?",
    "Deus prometeu que a semente da mulher feriria a cabeça da serpente (Gênesis 3:15) — a primeira profecia messiânica, apontando para Cristo."
))

for n in range(4, 51):
    gen_short = {4:("Caim e Abel","Caim e Abel ofereceram sacrifícios. Deus aceitou o de Abel, mas rejeitou o de Caim. Caim matou Abel por ciúmes.","Deus se importa com o coração por trás da oferta, não apenas com o presente em si. A fé de Abel o tornou justo. O pecado jaz à porta — precisamos dominá-lo.","O que levou Caim a matar seu irmão Abel?","O ciúmes porque Deus aceitou a oferta de Abel e rejeitou a sua. O pecado já estava à porta (Gênesis 4:6-7)."),
    5:("A Genealogia de Adão a Noé","A genealogia de Adão até Noé. Enoque andou com Deus e foi poupado da morte. Matusalém viveu 969 anos. Noé nasceu como consolo.","Cada nome nesta genealogia é um elo na promessa do Redentor. Em meio à morte que atingia a todos, Enoque escapou porque andava com Deus.","Quem andou com Deus e não viu a morte?","Enoque, que andou com Deus e foi tomado por Deus (Gênesis 5:24)."),
    6:("A Corrupção e a Arca de Noé","A maldade humana multiplicou-se. Deus decidiu destruir a terra, mas Noé achou graça. Deus ordenou que Noé construísse uma arca.","No meio da corrupção geral, um homem se destacou: Noé andava com Deus. A arca é símbolo da salvação que Deus provê para quem confia nEle.","O que diferenciou Noé das demais pessoas?","Noé era justo, reto e andava com Deus; achou graça aos olhos do Senhor (Gênesis 6:8-9)."),
    7:("O Dilúvio","Noé entrou na arca com sua família e os animais. As janelas dos céus se abriram e choveu 40 dias. As águas cobriram toda a terra.","O dilúvio mostra que Deus leva o pecado a sério, mas também que Ele preserva quem confia nEle. O juízo e a graça andam juntos.","Quanto tempo durou a chuva do dilúvio?","Quarenta dias e quarenta noites (Gênesis 7:12)."),
    8:("As Águas Baixam","Deus lembrou-se de Noé. As águas baixaram, a arca repousou no monte Ararate. Noé soltou uma pomba que voltou com folha de oliveira.","'Lembrou-se Deus de Noé' — que frase linda! Deus não esquece os seus. A pomba com a folha de oliveira é sinal de esperança e novos começos.","Qual foi o sinal de que as águas haviam baixado?","A pomba voltou com uma folha de oliveira no bico (Gênesis 8:11)."),
    9:("A Aliança com Noé","Deus abençoou Noé e seus filhos e estabeleceu uma aliança: não destruiria mais a terra com dilúvio. O arco-íris é o sinal dessa aliança.","O arco-íris é mais que um fenômeno natural — é sinal da fidelidade de Deus. Em Cristo temos uma aliança maior, selada com sangue na cruz.","Qual foi o sinal da aliança de Deus com Noé?","O arco-íris nas nuvens (Gênesis 9:13-15)."),
    10:("As Gerações dos Filhos de Noé","As genealogias de Sem, Cão e Jafé, de quem se originaram as nações. Ninrode foi um valente caçador.","Cada nome representa um povo. Deus se importa com todas as nações. A promessa de que em Abraão todas as famílias seriam benditas começa aqui.","Qual descendente de Cão se destacou como caçador?","Ninrode, que começou a ser poderoso na terra (Gênesis 10:8-9)."),
    11:("A Torre de Babel","A humanidade construiu uma torre para alcançar os céus. Deus confundiu as línguas e os espalhou pela terra.","Babel representa o orgulho humano de alcançar o céu por conta própria. Pentecostes inverte Babel: o Espírito Santo uniu as línguas no louvor a Deus.","Por que Deus confundiu as línguas em Babel?","Porque em seu orgulho queriam fazer nome para si mesmos, rebelando-se contra Deus (Gênesis 11:4-8)."),
    12:("O Chamado de Abrão","Deus chamou Abrão para sair de sua terra e prometeu fazer dele uma grande nação. Abrão partiu pela fé aos 75 anos.","Abrão não sabia para onde ia, mas confiou em Deus. A fé começa com um passo — sair da zona de conforto e seguir a direção de Deus.","Qual era a idade de Abrão quando partiu?","Setenta e cinco anos (Gênesis 12:4)."),
    13:("Abraão e Ló se Separam","Abrão e Ló se separaram porque a terra não os sustentava. Abrão deu a Ló a primeira escolha. Ló escolheu a campina fértil e foi para perto de Sodoma.","A generosidade de Abrão confiava em Deus como provedor. Ló escolheu pelo que via — mas isso o levou para perigo. A fé nos convida a escolher confiando em Deus.","Que atitude Abrão tomou na contenda com Ló?","Deu a Ló a primeira escolha de terra (Gênesis 13:8-9)."),
    14:("Abraão Resgata Ló","Abrão resgatou Ló dos reis invasores com 318 servos. Melquisedeque, rei de Salém, trouxe pão e vinho e abençoou Abrão, que deu o dízimo.","Melquisedeque é figura de Cristo, Rei-Sacerdote. Abrão deu o dízimo e recusou bens do rei de Sodoma para que ninguém dissesse que o enriqueceu.","Quem Abrão encontrou após a batalha?","Melquisedeque, que trouxe pão e vinho e o abençoou (Gênesis 14:18-19)."),
    15:("A Aliança com Abraão","Deus prometeu a Abrão descendência como as estrelas. Abrão creu em Deus, e isso lhe foi imputado por justiça. Deus fez uma aliança formal com ele.","Abraão creu em Deus, e isso lhe foi creditado como justiça — a base da salvação pela fé em toda a Escritura. A justiça não é conquistada, é recebida pela fé.","O que aconteceu quando Abrão creu em Deus?","Foi-lhe imputado por justiça (Gênesis 15:6)."),
    16:("Hagar e Ismael","Sarai, impaciente, deu sua serva Hagar a Abrão. Hagar concebeu Ismael. Mais tarde, Hagar fugiu e o anjo a encontrou no deserto.","A impaciência de Sarai e Abraão criou problemas duradouros. Mas Deus cuidou de Hagar e Ismael. Ele é 'o Deus da vista' — que nos vê em meio às lutas.","Como Hagar chamou o SENHOR que falou com ela?","'Tu és Deus da vista' (El-Roi) (Gênesis 16:13)."),
    17:("A Circuncisão","Deus mudou o nome de Abrão para Abraão e de Sarai para Sara. A circuncisão foi estabelecida como sinal da aliança. Isaque seria o filho da promessa.","Deus chama à existência o que ainda não existe. Abraão riu diante da promessa, mas Deus não desistiu. O que Deus promete, Ele cumpre.","Que mudanças de nome Deus fez?","Abrão para Abraão ('pai de muitas nações') e Sarai para Sara ('princesa') (Gênesis 17:5, 15)."),
    18:("A Intercessão por Sodoma","Deus visitou Abraão e prometeu um filho a Sara. Abraão intercedeu por Sodoma, pedindo que Deus poupasse a cidade se houvesse justos nela.","A intercessão de Abraão é exemplo de oração perseverante. Ele se aproximou com humildade. A presença de poucos justos pode fazer diferença.","Até quantos justos Abraão intercedeu?","De cinquenta até dez (Gênesis 18:32)."),
    19:("A Destruição de Sodoma","Os anjos vieram a Ló. Os homens de Sodoma cercaram a casa. Os anjos tiraram Ló e sua família. Deus destruiu Sodoma com fogo. A mulher de Ló olhou para trás e virou estátua de sal.","A mulher de Ló olhou para trás — seu coração ainda estava em Sodoma. Jesus disse: 'Lembrai-vos da mulher de Ló'. Seguir a Deus requer olhar para frente.","O que aconteceu com a mulher de Ló?","Tornou-se uma estátua de sal (Gênesis 19:26)."),
    20:("Abraão e Abimeleque","Abraão mentiu sobre Sara, dizendo que era sua irmã. Abimeleque a tomou, mas Deus o advertiu em sonho. Abraão orou por Abimeleque.","Até os heróis da fé têm fraquezas. Abraão ainda não confiava plenamente que Deus poderia protegê-lo. Deus é fiel mesmo quando somos infiéis.","Por que Abraão disse que Sara era sua irmã?","Temeu que o matassem por causa dela, pois não havia temor de Deus no lugar (Gênesis 20:11)."),
    21:("O Nascimento de Isaque","Sara concebeu e deu à luz Isaque. Ismael zombou de Isaque e Sara pediu que Hagar e Ismael fossem mandados embora. Deus cuidou de Ismael no deserto.","Depois de 25 anos de espera, Deus cumpriu a promessa. Isaque significa 'riso'. Deus transforma nossa incredulidade em celebração.","O que significa o nome Isaque?","'Riso' — porque Abraão e Sara riram quando Deus prometeu e riram de alegria quando se cumpriu (Gênesis 21:6)."),
    22:("O Sacrifício de Isaque","Deus pediu que Abraão sacrificasse Isaque. Abraão obedeceu. No último momento, Deus proveu um carneiro. Abraão chamou o lugar 'O SENHOR Proverá'.","Abraão confiava que Deus poderia ressuscitar Isaque. Deus proveu o cordeiro. Milhares de anos depois, outro Pai ofereceria Seu Filho no Calvário.","O que Abraão disse quando Isaque perguntou sobre o cordeiro?","'Deus proverá para si o cordeiro, meu filho' (Gênesis 22:8)."),
    23:("A Morte de Sara","Sara morreu aos 127 anos. Abraão comprou o campo de Macpela para sepultá-la.","A única terra que Abraão possuiu em Canaã foi um sepulcro — lembrando que nossa verdadeira herança está no céu.","Quanto Abraão pagou por Macpela?","Quatrocentos siclos de prata (Gênesis 23:15-16)."),
    24:("O Casamento de Isaque","Abraão enviou seu servo para encontrar esposa para Isaque. O servo orou por um sinal e Rebeca surgiu, dando água a ele e aos camelos. Rebeca casou-se com Isaque.","O servo orou e Deus respondeu antes que terminasse de falar. Rebeca foi abençoada por sua generosidade. Deus se importa com os relacionamentos.","Que sinal o servo pediu a Deus?","Que a moça que lhe desse água e também aos camelos fosse a escolhida (Gênesis 24:14)."),
    25:("Morte de Abraão e Nascimento de Esaú e Jacó","Abraão morreu aos 175 anos. Rebeca deu à luz Esaú e Jacó. Esaú vendeu sua primogenitura a Jacó por um prato de guisado.","Abraão morreu 'velho e farto de dias'. Esaú trocou sua herança por um prato de comida. Quantas vezes trocamos o eterno pelo imediato?","O que Esaú vendeu a Jacó?","Sua primogenitura por um prato de guisado (Gênesis 25:33-34)."),
    26:("Isaque e Abimeleque","Deus apareceu a Isaque e o abençoou. Os filisteus o invejavam e entupiam seus poços. Isaque cavou novos poços até chegar a Reobote.","Isaque foi paciente. Em vez de lutar, cavou outro poço. Em Reobote, Deus lhe deu espaço. A paciência é recompensada por Deus.","Por que Isaque chamou o poço de Reobote?","'Agora nos deu lugar o SENHOR, e cresceremos na terra' (Gênesis 26:22)."),
    27:("Jacó Recebe a Bênção","Rebeca ajudou Jacó a enganar Isaque e receber a bênção destinada a Esaú. Esaú odiou Jacó e planejou matá-lo. Jacó fugiu.","O engano trouxe divisão. Quando tentamos apressar os planos de Deus, criamos problemas que duram gerações. Confie no tempo de Deus.","Como Jacó enganou Isaque?","Vestiu as roupas de Esaú e cobriu as mãos com peles de cabrito (Gênesis 27:15-16)."),
    28:("A Escada de Jacó","Jacó fugiu para Harã. No caminho, sonhou com uma escada que ligava o céu e a terra. Deus prometeu estar com ele. Jacó chamou o lugar Betel.","Sozinho no deserto, dormindo sobre uma pedra, Deus veio ao encontro de Jacó. A escada aponta para Jesus, a ponte entre Deus e a humanidade.","O que Jacó viu em seu sonho?","Uma escada que ligava a terra ao céu, com anjos subindo e descendo (Gênesis 28:12-13)."),
    29:("Jacó e Raquel","Jacó encontrou Raquel e se apaixonou. Serviu Labão 7 anos por ela, mas recebeu Lia. Serviu mais 7 anos por Raquel.","O amor de Jacó por Raquel perseverou: 7 anos pareceram poucos dias. Mas ele colheu o que plantou — enganou seu pai e foi enganado por Labão.","Quanto tempo Jacó serviu por Raquel?","Sete anos, que pareceram como poucos dias pelo amor que lhe tinha (Gênesis 29:20)."),
    30:("Os Filhos de Jacó","Lia e Raquel rivalizaram. Nasceram os 11 primeiros filhos de Jacó: Rúben, Simeão, Levi, Judá, Dã, Naftali, Gade, Aser, Issacar, Zebulom e José.","A rivalidade trouxe frustração, mas Deus era soberano. José seria o instrumento de Deus para preservar a família. Nossas imperfeições não impedem o plano de Deus.","Qual foi o nome do primogênito de Raquel?","José (Gênesis 30:22-24)."),
    31:("Jacó Foge de Labão","Jacó fugiu de Labão com sua família. Labão o perseguiu, mas Deus o advertiu em sonho. Fizeram uma aliança.","Chega o momento de sair de situações tóxicas. Deus vai adiante de nós preparando o caminho.","O que Deus disse a Labão em sonho?","'Guarda-te que não fales a Jacó nem bem nem mal' (Gênesis 31:24)."),
    32:("Jacó Luta com Deus","Jacó lutou com um varão até o amanhecer. Recebeu o nome de Israel ('príncipe de Deus'). Viu a Deus face a face e sua vida foi poupada.","Jacó lutou com pessoas a vida toda, mas sua maior luta foi com Deus. Ele foi quebrado para ser transformado. O novo nome significa nova identidade.","Que nome Deus deu a Jacó?","Israel, que significa 'príncipe de Deus' (Gênesis 32:28)."),
    33:("A Reconciliação com Esaú","Esaú encontrou Jacó e, em vez de vingança, o abraçou e beijou. Os irmãos se reconciliaram depois de 20 anos.","A reconciliação entre irmãos é uma das cenas mais emocionantes da Bíblia. O perdão é um milagre.","Como Esaú reagiu ao encontrar Jacó?","Abraçou-o, beijou-o, e ambos choraram (Gênesis 33:4)."),
    34:("O Caso de Diná","Siquém violentou Diná. Simeão e Levi se vingaram, matando todos os homens da cidade. Jacó os repreendeu.","A violência gera mais violência. A vingança não traz justiça verdadeira. A resposta de Deus ao mal não é vingança, mas redenção.","Como Simeão e Levi reagiram?","Mataram todos os homens de Siquém em vingança (Gênesis 34:25-26)."),
    35:("Jacó Volta a Betel","Deus chamou Jacó de volta a Betel. Ele purificou sua casa. Raquel morreu ao dar à luz Benjamim. Isaque morreu aos 180 anos.","Deus chamou Jacó de volta ao lugar do encontro original. A vida cristã tem Betel (encontro com Deus) e Efrata (lágrimas), mas Deus está em ambos.","O que Jacó pediu antes de subir a Betel?","Lançar fora os deuses estranhos e se purificar (Gênesis 35:2)."),
    36:("As Gerações de Esaú","As genealogias de Esaú (Edom). Ele se mudou para a região de Seir porque suas possessões eram grandes demais.","Esaú também foi abençoado por Deus. A história mostra que Deus está no controle de todas as nações, não apenas de Israel.","Para onde Esaú se mudou?","Para Seir (Edom) (Gênesis 36:6-8)."),
    37:("José Vendido pelos Irmãos","Jacó amava José mais que aos outros. José sonhou que seus irmãos se curvariam a ele. Os irmãos o venderam por 20 moedas de prata. Levaram-no ao Egito.","Entre o sonho e o cumprimento há um vale de sofrimento. José foi traído e vendido, mas Deus estava no controle. O sonho de Deus passa pelo vale antes de chegar ao palácio.","Por quanto José foi vendido?","Vinte peças de prata (Gênesis 37:28)."),
    38:("Judá e Tamar","Judá não cumpriu sua promessa a Tamar. Ela se disfarçou e Judá a engravidou. Judá reconheceu: 'Mais justa é do que eu'. Tamar está na genealogia de Jesus.","Deus redime até as histórias mais complicadas. Tamar é mencionada na genealogia de Jesus. A graça de Deus alcança onde a justiça humana falha.","O que Judá reconheceu sobre Tamar?","'Mais justa é do que eu' (Gênesis 38:26)."),
    39:("José e a Mulher de Potifar","José prosperou na casa de Potifar. A mulher de Potifar tentou seduzi-lo, mas José recusou: 'Pecaria contra Deus?' Foi preso injustamente.","José resistiu à tentação por temor a Deus. Sua integridade lhe custou a liberdade, mas Deus estava com ele. A fidelidade nas pequenas coisas prepara para as grandes.","Qual foi a resposta de José à tentação?","'Como faria eu este tamanho mal e pecaria contra Deus?' (Gênesis 39:9)."),
    40:("José Interpreta Sonhos na Prisão","O copeiro e o padeiro de Faraó foram presos. José interpretou seus sonhos: o copeiro seria restaurado, o padeiro executado. O copeiro esqueceu-se de José.","José servia mesmo na prisão. Ele deu crédito a Deus. Mas o copeiro se esqueceu dele. Deus muitas vezes nos faz esperar para nos preparar.","O copeiro lembrou-se de José?","Não, esqueceu-se dele por dois anos (Gênesis 40:23)."),
    41:("José Interpreta os Sonhos de Faraó","Faraó sonhou com vacas e espigas. José interpretou: 7 anos de fartura seguidos de 7 de fome. Faraó nomeou José governador do Egito.","Em um dia, José passou da prisão ao palácio. Sua humildade brilha: 'Isso não está em mim; Deus dará resposta.' Nossas provações nos preparam para bênçãos maiores.","Que cargo Faraó deu a José?","Governador de todo o Egito (Gênesis 41:40-41)."),
    42:("Os Irmãos de José no Egito","A fome trouxe os irmãos de José ao Egito. Eles se curvaram diante dele, cumprindo os sonhos. José os testou e prendeu Simeão.","Vinte e dois anos depois, os sonhos se cumpriram. A consciência dos irmãos falou: 'Somos culpados acerca de nosso irmão'. O pecado sempre ressurge.","Do que os irmãos se lembraram?","'Na verdade somos culpados acerca de nosso irmão' (Gênesis 42:21)."),
    43:("Os Irmãos Voltam com Benjamim","Jacó relutou em enviar Benjamim, mas Judá se ofereceu como fiador. José viu Benjamim e chorou. Preparou um banquete.","José retirou-se para chorar. Vinte e dois anos de saudade transbordaram. O perdão não é fingir que nada aconteceu, mas escolher amar apesar da dor.","O que José fez quando viu Benjamim?","Suas entranhas se comoveram, e ele chorou (Gênesis 43:30)."),
    44:("A Prova do Cálice","José colocou seu cálice no saco de Benjamim. Judá se ofereceu como escravo no lugar do irmão.","Judá, que propusera vender José, agora se oferecia para morrer por Benjamim. A transformação era real. Isso aponta para Cristo, nosso substituto.","O que Judá se ofereceu para fazer?","Ficar como escravo no lugar de Benjamim (Gênesis 44:33)."),
    45:("José se Revela","José revelou sua identidade aos irmãos e chorou. 'Não fostes vós que me enviastes, senão Deus.' Mandou buscar seu pai.","José ofereceu perdão. 'Vós intentastes o mal, mas Deus o tornou em bem.' Alguém que entende a graça de Deus não pode negar graça aos outros.","Qual foi a primeira coisa que José disse?","'Eu sou José... não vos entristeçais; Deus me enviou adiante de vós' (Gênesis 45:4-5)."),
    46:("Jacó Desce ao Egito","Deus confirmou a Jacó: 'Não temas descer ao Egito.' José encontrou seu pai em Gósen. Jacó disse: 'Já posso morrer, pois vi o teu rosto.'","Jacó finalmente reencontrou José. Deus disse 'Não temas'. O que começou com um sonho terminou na preservação de uma nação.","Quantas pessoas foram ao Egito?","Setenta almas (Gênesis 46:27)."),
    47:("Jacó no Egito","Faraó deu a terra de Gósen a Jacó. José sustentou sua família durante a fome. Jacó abençoou Faraó.","Jacó, o peregrino, abençoou o faraó. O povo de Deus é portador de bênção. Mesmo em tempos de escassez, Deus pode nos fazer frutificar.","Com quantos anos Jacó chegou ao Egito?","Cento e trinta anos (Gênesis 47:9)."),
    48:("Jacó Abençoa Efraim e Manassés","Jacó abençoou os filhos de José, Efraim e Manassés. Colocou a mão direita sobre Efraim, o mais novo, invertendo a ordem natural.","Deus não segue as regras humanas de primogenitura. Ele escolhe os improváveis para mostrar Sua graça. A bênção de Deus desafia nossa lógica.","Qual filho recebeu a mão direita?","Efraim, o mais novo (Gênesis 48:14-19)."),
    49:("Jacó Abençoa Seus Filhos","Jacó profetizou sobre cada filho: Rúben perdeu a primogenitura, Judá recebeu o cetro, José foi o ramo frutífero.","O leito de morte de Jacó é um palco profético. Judá recebeu a promessa do Messias. Siló (o Messias) viria da tribo de Judá.","Qual tribo recebeu a promessa do cetro real?","Judá, de quem viria Siló (o Messias) (Gênesis 49:10)."),
    50:("Morte de Jacó e de José","José sepultou Jacó em Canaã. Perdoou os irmãos: 'Vós intentastes o mal, mas Deus o tornou em bem'. José morreu aos 110 anos, confiando na promessa de Deus.","Gênesis termina com um caixão no Egito, mas com a promessa: 'Deus certamente vos visitará'. O mal não tem a última palavra. Deus redime, restaura e cumpre.","Qual foi a mensagem final de José?","'Deus certamente vos visitará e vos fará subir desta terra' (Gênesis 50:24-25).")}
    t = gen_short[n]
    genesis_chapters.append(chapter_js(n, t[0], t[1], t[2], t[3], t[4]))

books.append('''  {
    id: "genesis",
    name: "Gênesis",
    testament: "Antigo Testamento",
    totalChapters: 50,
    chapters: [\n''' + ',\n'.join(genesis_chapters) + '''\n    ]
  },''')

# ====== EXODUS (40 chapters) ======
exodus_chapters = []

exodus_chapters.append(chapter_js(1,
    "Israel Oprimido no Egito",
    "Estes são os nomes dos filhos de Israel que vieram ao Egito com Jacó. José morreu, e todos os daquela geração. Os filhos de Israel multiplicaram-se.\n\nSurgiu um novo rei sobre o Egito que não conhecera a José, e temeu o povo de Israel. Puseram sobre eles feitores para os oprimirem com cargas pesadas.\n\nO rei do Egito ordenou que os bebês hebreus fossem mortos. As parteiras, porém, temeram a Deus e não obedeceram ao rei.",
    "Quanto mais oprimiam Israel, mais se multiplicavam. Deus trabalhava no silêncio. As parteiras temeram a Deus e desobedeceram ao rei — exemplo de que devemos obedecer a Deus antes que aos homens.",
    "O que as parteiras fizeram quando Faraó ordenou matar os bebês?",
    "Elas temeram a Deus e não obedeceram ao rei, poupando os bebês (Êxodo 1:17)."
))

exodus_chapters.append(chapter_js(2,
    "O Nascimento e Fuga de Moisés",
    "Moisés nasceu e foi escondido por três meses. Sua mãe o colocou num cesto no rio. A filha de Faraó o encontrou e teve compaixão. Miriã trouxe a própria mãe para amamentá-lo.\n\nMoisés foi criado no palácio. Quando adulto, viu um egípcio maltratando um hebreu e o matou. Faraó procurou matá-lo, e Moisés fugiu para Midiã.",
    "Deus preparou Moisés no palácio (educação) e no deserto (humildade). O homem que agiu por impulso seria transformado no líder mais manso da terra.",
    "Quem salvou Moisés do rio e quem o criou?",
    "A filha de Faraó o salvou; sua própria mãe o criou como ama (Êxodo 2:5-9)."
))

exodus_chapters.append(chapter_js(3,
    "A Sarça Ardente",
    "Moisés apascentava as ovelhas no monte Horebe. O Anjo do SENHOR apareceu numa sarça que ardia sem se consumir. Deus disse: Tira os sapatos, porque este lugar é santo.\n\nEu sou o Deus de Abraão, Isaque e Jacó. Vi a aflição do meu povo. Vem, enviar-te-ei a Faraó.\n\nMoisés disse: Quem sou eu? Deus disse: Eu serei contigo. Qual é o teu nome? EU SOU O QUE SOU.",
    "A sarça ardente: um pastor humilde é chamado para libertar uma nação. Deus se revela como 'EU SOU' — auto-existente e presente. Não é nossa capacidade que importa, mas a presença de Deus conosco.",
    "Qual nome Deus revelou a Moisés?",
    "EU SOU O QUE SOU (YHWH) — Êxodo 3:14."
))

for n in range(4, 41):
    ex_short = {4:("Os Sinais de Moisés","Deus deu a Moisés três sinais: vara que vira cobra, mão leprosa e água que vira sangue. Moisés hesitou por não ser eloqüente. Deus disse: Eu serei com a tua boca.","Deus usa o que temos. 'Que é isso na tua mão?' Nossas limitações não são obstáculos para Deus — Ele as usa para mostrar Seu poder.","Quais foram os três sinais?","A vara que virou cobra, a mão leprosa e a água que virou sangue (Êxodo 4:2-9)."),
    5:("Moisés e Arão Falam com Faraó","Moisés e Arão pediram a Faraó que libertasse Israel. Faraó recusou e aumentou a opressão: não deu palha ao povo. Moisés questionou a Deus.","O primeiro confronto pareceu um fracasso. Muitas vezes, quando obedecemos a Deus, as coisas pioram antes de melhorar. O aparente fracasso precede o maior livramento.","Como Faraó reagiu?","Recusou e aumentou a opressão, não dando palha mas exigindo os mesmos tijolos (Êxodo 5:7-8)."),
    6:("Deus Renova a Promessa","Deus disse a Moisés: Eu sou o SENHOR. Apareci a Abraão, Isaque e Jacó. Estabeleci minha aliança. Eu vos tirarei do Egito. Mas o povo não ouvia por causa da aflição.","Deus reafirma a promessa, mas o povo oprimido não conseguia ouvir. A dor intensa pode nos impedir de enxergar a esperança. Deus entende e persiste.","Por que Israel não ouviu Moisés?","Por causa da angústia de espírito e da dura servidão (Êxodo 6:9)."),
    7:("A Primeira Praga: Águas em Sangue","Arão lançou a vara e ela virou serpente. Os magos imitaram. Moisés feriu o Nilo com a vara, e as águas viraram sangue. Faraó endureceu o coração.","A primeira praga demonstra o poder de Deus sobre o deus Nilo. Faraó endureceu o coração. O coração que resiste a Deus torna-se cada vez mais duro.","Em que a primeira praga transformou as águas?","Em sangue (Êxodo 7:20-21)."),
    8:("Rãs, Piolhos e Moscas","Deus enviou pragas de rãs, piolhos e moscas. Faraó pediu alívio, mas endureceu o coração quando o alívio veio. Os magos reconheceram: 'Isto é o dedo de Deus'.","Faraó fez promessas na crise que esqueceu na bonança. Quantas vezes fazemos o mesmo com Deus?","O que os magos disseram sobre os piolhos?","'Isto é o dedo de Deus' (Êxodo 8:19)."),
    9:("Praga nos Animais, Úlceras e Saraiva","Peste matou o gado egípcio, mas poupou o de Israel. Úlceras feriram homens e animais. Saraiva destruiu plantações. Faraó disse 'Pequei', mas depois endureceu o coração.","Pela primeira vez Deus fez separação entre Israel e o Egito. Faraó confessou 'Pequei' mas era arrependimento superficial.","O que diferenciou Israel?","Na terra de Gósen não houve saraiva (Êxodo 9:26)."),
    10:("Gafanhotos e Trevas","Gafanhotos devoraram o que restou. Trevas cobriram o Egito por três dias, mas Israel tinha luz. Faraó quis negociar, mas Moisés exigiu liberdade total.","Faraó queria o livramento nos seus termos. Deus não negocia. Ele exige obediência total. Israel tinha luz — Jesus é a luz do mundo.","O que Faraó exigiu que ficasse?","Os rebanhos e o gado (Êxodo 10:24)."),
    11:("O Anúncio da Décima Praga","Moisés anunciou a última praga: todo primogênito no Egito morreria. Israel foi instruído a pedir jóias aos egípcios. Moisés saiu da presença de Faraó com ira.","A décima praga atingiria o coração do Egito. Para Israel, a salvação viria pelo sangue de um cordeiro no umbral da porta.","Qual foi a última praga?","Morte de todo primogênito no Egito (Êxodo 11:4-5)."),
    12:("A Páscoa e a Saída do Egito","Deus instituiu a Páscoa: um cordeiro por família, sangue nos umbrais. À meia-noite, os primogênitos morreram. Faraó expulsou Israel. 600 mil homens saíram do Egito.","A Páscoa aponta para Cristo, o Cordeiro de Deus. 'Quando eu vir o sangue, passarei por vós'. A salvação não vem por mérito, mas pelo sangue.","O que os israelitas colocaram nos umbrais?","O sangue do cordeiro pascal (Êxodo 12:7, 13)."),
    13:("A Consagração dos Primogênitos","Deus ordenou santificar os primogênitos. Moisés levou os ossos de José. Deus guiou Israel com coluna de nuvem de dia e fogo de noite.","Moisés levou os ossos de José — promessa de 400 anos se cumprindo. A coluna de nuvem e fogo é a presença visível de Deus guiando Seu povo.","Como Deus guiou Israel?","Coluna de nuvem de dia e coluna de fogo de noite (Êxodo 13:21-22)."),
    14:("A Travessia do Mar Vermelho","Israel acampou junto ao mar. Faraó os perseguiu. Moisés disse: 'Não temais; estai quietos e vede o livramento do SENHOR'. O mar se abriu e Israel passou em seco. Os egípcios morreram.","O maior milagre do Êxodo. Encurralados, Deus abriu o mar. 'Estai quietos e vede' — quando não podemos fazer nada, Deus age.","O que Moisés disse ao povo?","'Estai quietos e vede o livramento do SENHOR' (Êxodo 14:13-14)."),
    15:("O Cântico de Moisés","Moisés e Israel cantaram: 'Cantarei ao SENHOR, porque triunfou gloriosamente'. Miriã liderou as mulheres com tamborins e danças. O povo chegou a Elim, onde havia 12 fontes.","O louvor é a resposta natural ao livramento de Deus. Miriã liderou a adoração comunitária. Depois do milagre, Deus levou o povo a um oásis de descanso.","Quem liderou as mulheres em dança?","Miriã, a profetisa (Êxodo 15:20-21)."),
    16:("O Maná do Céu","O povo murmurou por comida. Deus enviou maná do céu. Cada dia colhiam a porção necessária. Ao sexto dia, colhiam o dobro para o sábado. Quem guardou para o dia seguinte viu bichos.","O maná ensina dependência diária de Deus. 'O pão nosso de cada dia nos dá hoje'. Jesus é o verdadeiro pão do céu.","O que acontecia com o maná guardado?","Criava bichos e cheirava mal (Êxodo 16:20)."),
    17:("Água da Rocha e Vitória sobre Amaleque","O povo murmurou por água. Deus mandou Moisés ferir a rocha, e água jorrou. Amaleque atacou Israel. Moisés levantou as mãos com a vara, e Josué venceu.","A rocha ferida é figura de Cristo. Quando Moisés levantava as mãos, Israel vencia. Arão e Hur sustentaram suas mãos — ninguém vence sozinho.","O que Moisés fez para Israel vencer?","Levantou as mãos com a vara; quando as mãos subiam, Israel prevalecia (Êxodo 17:11-12)."),
    18:("O Conselho de Jetro","Jetro visitou Moisés e reconheceu o Deus de Israel. Viu Moisés julgando o povo sozinho e aconselhou-o a delegar: chefes de mil, cem, cinquenta e dez. Moisés ouviu.","Liderar não é fazer tudo, mas capacitar outros. Jetro, um midianita, deu sábio conselho. Moisés foi humilde para ouvir.","Qual foi o conselho de Jetro?","Escolher homens capazes para julgar causas menores (Êxodo 18:17-22)."),
    19:("Israel no Monte Sinai","Israel chegou ao Sinai. Deus disse: 'Vos levei sobre asas de águias. Sereis reino sacerdotal e nação santa'. O povo respondeu: 'Faremos tudo'. Deus desceu em fogo e trovões.","A lei foi dada a um povo já redimido pela graça. A glória do Sinai aponta para a necessidade de um mediador — Jesus Cristo.","Qual foi a resposta do povo?","'Tudo o que o SENHOR tem falado faremos' (Êxodo 19:8)."),
    20:("Os Dez Mandamentos","Deus falou os Dez Mandamentos: I a IV sobre Deus (não ter outros deuses, não fazer imagens, não tomar Seu nome em vão, guardar o sábado). V a X sobre o próximo (honrar pai e mãe, não matar, não adulterar, não furtar, não mentir, não cobiçar). O povo tremeu.","A lei revela o padrão santo de Deus. O último mandamento (não cobiçar) revela que o pecado começa no coração. A lei nos mostra nossa necessidade de graça.","Quantos mandamentos e em que se dividem?","Dez: quatro sobre Deus e seis sobre o próximo (Êxodo 20:1-17)."),
    21:("Leis sobre Servos e Danos","Leis sobre servos hebreus (libertos no 7º ano), homicídio, ferimentos, danos causados por animais. 'Olho por olho, dente por dente.'","'Olho por olho' limitava a vingança — a punição não podia exceder o crime. Deus se importa com justiça proporcional.","O que significava 'olho por olho'?","Justiça proporcional: a punição não excede o dano (Êxodo 21:23-24)."),
    22:("Leis sobre Propriedade e Conduta","Leis sobre furto (restituição), danos a propriedade, empréstimos, sedução. Proteção ao estrangeiro, viúva e órfão: 'Não oprimirás o estrangeiro, pois fostes estrangeiros no Egito'.","O coração de Deus pelos vulneráveis transparece nestas leis. Israel deveria lembrar sua própria história de opressão.","Por que não oprimir o estrangeiro?","Porque Israel foi estrangeiro no Egito (Êxodo 22:21)."),
    23:("Leis de Justiça e Festas","'Não seguirás a multidão para fazeres mal'. Ano sabático para a terra descansar. Três festas anuais: Páscoa, Pentecostes e Tabernáculos. Deus prometeu um Anjo para guiá-los.","A justiça não pode ser manipulada pela multidão. As festas lembravam a provisão de Deus. O Anjo que guiou Israel aponta para a presença constante de Deus.","Quais eram as três festas?","Páscoa, Pentecostes e Tabernáculos (Êxodo 23:14-16)."),
    24:("A Confirmação da Aliança","Moisés escreveu a lei, construiu um altar e leu o livro da aliança. O povo disse: 'Faremos e obedeceremos'. Moisés aspergiu o sangue da aliança. Subiu ao monte com 70 anciãos.","A aliança foi selada com sangue — 'o sangue da aliança' aponta para Cristo. Moisés subiu ao monte por 40 dias. A intimidade com Deus requer tempo separado.","Quanto tempo Moisés ficou no monte?","Quarenta dias e quarenta noites (Êxodo 24:18)."),
    25:("A Oferta para o Tabernáculo","Deus ordenou que Israel trouxesse ofertas voluntárias: ouro, prata, bronze, tecidos, madeira, pedras preciosas. 'Far-me-ão um santuário, para que eu habite no meio deles.' Instruções para a arca, mesa e candelabro.","Deus deseja habitar no meio do Seu povo. Cada detalhe do tabernáculo aponta para Cristo. A oferta deveria ser voluntária — Deus ama quem dá com alegria.","Qual era o propósito do tabernáculo?","Para que Deus habitasse no meio do Seu povo (Êxodo 25:8)."),
    26:("O Tabernáculo e Suas Cortinas","Instruções detalhadas para as cortinas do tabernáculo: linho fino, pêlos de cabras, peles de carneiro. O véu separava o Lugar Santo do Santo dos Santos.","O véu separava a presença de Deus. Apenas o sumo sacerdote podia entrar, uma vez por ano. Quando Cristo morreu, o véu se rasgou — o acesso a Deus foi aberto para todos.","O que o véu separava?","O Lugar Santo do Santo dos Santos (Êxodo 26:33)."),
    27:("O Altar de Bronze e o Pátio","Instruções para o altar de holocaustos (madeira revestida de bronze), com chifros nos cantos. O pátio do tabernáculo cercado por cortinas de linho. Azeite para o candeeiro contínuo.","O altar de bronze era o lugar do sacrifício. 'Sem derramamento de sangue não há remissão.' O candeeiro aceso continuamente simbolizava a presença eterna de Deus.","O que era feito no altar de bronze?","Sacrifícios de animais para expiação dos pecados (Êxodo 27:1-8)."),
    28:("As Vestes Sacerdotais","Instruções para as vestes de Arão: peitoral com 12 pedras (nomes das tribos), estola, manto, túnica, mitra. Arão levaria os nomes de Israel sobre o coração diante de Deus.","O sumo sacerdote levava Israel sobre os ombros (força) e no coração (amor). Jesus é nosso Sumo Sacerdote que nos carrega diante do Pai.","O que Arão levava no peitoral?","Doze pedras com os nomes das tribos de Israel (Êxodo 28:21, 29)."),
    29:("A Consagração dos Sacerdotes","Ritual de consagração: lavagem, vestimenta, unção com óleo, sacrifícios. Holocausto contínuo: dois cordeiros por dia, um pela manhã e outro à tarde.","A consagração envolvia purificação e sacrifício. Em Cristo, somos feitos sacerdotes reais. Fomos lavados, ungidos e selados pelo Espírito de uma vez por todas.","O que era oferecido pela manhã e à tarde?","Dois cordeiros em holocausto contínuo (Êxodo 29:38-39)."),
    30:("O Altar do Incenso e o Censo","Altar de ouro para o incenso, queimado cada manhã e tarde. O incenso simboliza a oração do povo. Censo com resgate de meio siclo por pessoa. Bacia de bronze para lavagem.","O incenso representa a oração subindo a Deus. A bacia de bronze simboliza a purificação necessária antes de servir. Em Cristo, temos livre acesso ao trono da graça.","O que simbolizava o incenso?","As orações do povo subindo diante de Deus (Êxodo 30:1-8)."),
    31:("Bezalel e o Sábado","Deus escolheu Bezalel (da tribo de Judá) e Aoliabe (de Dã), enchendo-os do Espírito de Deus para a obra. O sábado é o sinal da aliança. Moisés recebeu as tábuas de pedra.","Deus capacita pessoas para o trabalho sagrado. Bezalel foi cheio do Espírito para artesanato. O sábado lembra que Deus é quem nos santifica.","Quem Deus encheu com Seu Espírito?","Bezalel e Aoliabe para construir o tabernáculo (Êxodo 31:2-6)."),
    32:("O Bezerro de Ouro","Moisés tardou no monte. O povo fez um bezerro de ouro. Deus quis destruí-los, mas Moisés intercedeu. Moisés quebrou as tábuas. Os levitas se colocaram ao lado do SENHOR.","O bezerro de ouro representa a infidelidade de Israel. Trocaram a glória de Deus por um ídolo. Moisés intercedeu — a intercessão pode mudar o curso da história.","O que Moisés fez com as tábuas?","Quebrou-as ao pé do monte (Êxodo 32:19)."),
    33:("A Intercessão de Moisés","Deus disse que enviaria um anjo, mas não iria pessoalmente. Moisés disse: 'Se Tua presença não for conosco, não nos faças subir'. Pediu para ver a glória de Deus. Deus o colocou na fenda da rocha.","Moisés não queria a terra prometida sem a presença de Deus. 'Se Tua presença não for conosco, não nos faças subir.' A presença de Deus é mais importante que as bênçãos.","O que Moisés disse sobre a presença de Deus?","'Se a Tua presença não for conosco, não nos faças subir' (Êxodo 33:15)."),
    34:("Novas Tábuas e o Rosto Radiante","Deus renovou a aliança. Moisés subiu ao monte com novas tábuas. Deus proclamou: 'SENHOR, Deus misericordioso e piedoso, tardio em irar-se'. Moisés desceu com o rosto resplandecente.","A revelação mais profunda de Deus: Sua glória é Seu caráter. 'Deus misericordioso e piedoso'. Moisés resplandeceu por estar na presença de Deus.","O que aconteceu ao rosto de Moisés?","Resplandecia porque falara com Deus (Êxodo 34:29-30)."),
    35:("A Oferta para o Tabernáculo","Moisés convocou o povo para trazer ofertas voluntárias. O povo trouxe tanto que Moisés teve que parar a coleta — havia material mais que suficiente para a obra.","A oferta foi tão generosa que precisaram parar de receber. Deus ama quem dá com alegria. Quando damos a Deus de coração, Ele sempre provê abundantemente.","Por que Moisés mandou parar as ofertas?","O material era suficiente e mais que suficiente (Êxodo 36:4-7)."),
    36:("A Construção do Tabernáculo","Os artífices construíram o tabernáculo conforme a ordem de Deus: cortinas, tábuas, colchetes, o véu. Tudo foi feito exatamente como o SENHOR havia ordenado a Moisés.","Deus valoriza os detalhes. A obediência cuidadosa na construção reflete a importância de fazer tudo conforme a Palavra. Nosso corpo é o templo do Espírito Santo.","Como Israel construiu o tabernáculo?","Conforme tudo o que o SENHOR ordenara a Moisés (Êxodo 39:42-43)."),
    37:("A Arca, a Mesa e o Candelabro","Bezalel fez a arca de madeira revestida de ouro, o propiciatório com querubins, a mesa dos pães da proposição e o candelabro de ouro batido com sete braços.","A arca com o propiciatório era o centro da presença de Deus. O candelabro aponta para Jesus, a luz do mundo. Bezalel usou seus talentos para a glória de Deus.","O que os querubins cobriam?","O propiciatório sobre a arca (Êxodo 37:6-9)."),
    38:("O Altar do Holocausto e a Bacia","Fez-se o altar de bronze para holocaustos, a bacia de bronze dos espelhos das mulheres que serviam, e o pátio com cortinas de linho e colunas de bronze.","A bacia foi feita dos espelhos das mulheres — símbolo de que a verdadeira beleza está na pureza interna, não na reflexão externa.","De que foi feita a bacia?","Dos espelhos das mulheres que serviam (Êxodo 38:8)."),
    39:("As Vestes Sacerdotais","Confeccionaram-se as vestes de Arão: estola, peitoral com 12 pedras, manto, túnica e mitra. Tudo feito conforme o SENHOR ordenara. Moisés abençoou o povo.","Cada detalhe das vestes apontava para a dignidade do ministério sacerdotal. Jesus, nosso Sumo Sacerdote, nos carrega diante do Pai.","Quantas pedras no peitoral?","Doze, com os nomes das tribos (Êxodo 39:10-14)."),
    40:("A Glória do SENHOR Enche o Tabernáculo","Moisés levantou o tabernáculo. A nuvem cobriu a tenda da congregação, e a glória do SENHOR encheu o tabernáculo. Moisés não podia entrar. A nuvem guiava Israel em todas as jornadas.","Êxodo termina com a glória de Deus enchendo o tabernáculo. Começa com escravidão e termina com glória. A presença de Deus habitando no meio do Seu povo.","O que guiava Israel nas jornadas?","A nuvem de dia e o fogo de noite sobre o tabernáculo (Êxodo 40:36-38).")}
    t = ex_short[n]
    exodus_chapters.append(chapter_js(n, t[0], t[1], t[2], t[3], t[4]))

books.append('''  {
    id: "exodus",
    name: "Êxodo",
    testament: "Antigo Testamento",
    totalChapters: 40,
    chapters: [\n''' + ',\n'.join(exodus_chapters) + '''\n    ]
  }
]''')

# Write the complete file
with open('src/data/bibleData.js', 'w', encoding='utf-8') as f:
    f.write('export const BIBLE_DATA = [\n')
    f.write(books[0])
    f.write('\n')
    f.write(books[1])
    f.write('\n')

print("Generated bibleData.js complete!")
